### ISSUE TITLE
X axis shows datetime labels overlapped 

### ISSUE THREAD

**Issue by RaminderRandhawa91** [Arction/lcjs-example-0000-lineSeries#1]
`  const lsjs = this.libraryInstance;
      // Create a new axis so as to show date on X axis
      const xAxis = this.chartInstance.addAxisX().setTickStrategy(lsjs.AxisTickStrategies.DateTime,
         (tickStrategy) => tickStrategy
            // This will format a data-point with value 0 as current Date and Time.
            .setDateOrigin(new Date(dateOrigin))
            .setFormattingDay(
            { year: 'numeric', month: 'long' },
            { day: '2-digit' },
            { hour: '2-digit', minute: '2-digit' })
          .setMinorTickStyle(undefined)
          .setGreatTickStyle(this.libraryInstance.emptyTick))
          .setAnimationZoom(undefined)
          .setChartInteractionZoomByWheel(false)
          .setAnimationScroll(undefined);`
Here is how I am adding x axis and later I am displosing the deafult X -axis.
Please see attched screenshot showing how the hours of the date are being overlapped. 
![overlap](https://user-images.githubusercontent.com/16584440/100920665-71e6ca80-34a9-11eb-9ba4-dc2103afd018.PNG)

**Comment by Snekw** [comment]
Issues that aren't directly related to the repository should be either be posted to StackOverflow with `lightningchart` tag.

But this issue is a bug in our axis label code and we have created an issue on our internal systems to fix it in a future release.
